services:
  - type: web
    name: car-expert-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn darksite.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: darksite.settings
