# Generated by Django 5.2.1 on 2025-06-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[], max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année de fabrication')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilométrage (km)')),
                ('engine_type', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Électrique', 'Électrique')], max_length=50, verbose_name='Type de moteur')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Cylindrée (L)')),
                ('gearbox', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('CVT', 'CVT')], max_length=50, verbose_name='Boîte de vitesses')),
                ('drive', models.CharField(choices=[('2WD Avant', '2WD Avant'), ('2WD Arrière', '2WD Arrière'), ('4WD', '4WD')], max_length=20, verbose_name='Type de transmission')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='Photo principale')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_icons/', verbose_name='Icône (PNG/JPG/SVG)')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Photo supplémentaire')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255, verbose_name='Option')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix à partir de')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix jusqu'à")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.service')),
            ],
        ),
    ]
