const priceData = {
  "Ремонт двигателя": {
    sheetName: "Двигатель",
    data: [
      ["🔧 Diagnostic du moteur", "", ""],
      ["Diagnostic informatique", "30", ""],
      ["Vérification de la compression dans les cylindres", "50", ""],
      ["Diagnostic du système d'alimentation (carburant)", "50", ""],
      ["Diagnostic du système de refroidissement", "50", ""],
      ["Diagnostic du système de lubrification", "50", ""],
      ["⚙️ Réparation complète du moteur", "", ""],
      ["Démontage complet du moteur", "70 €/heure", ""],
      ["Nettoyage et contrôle des pièces", "70 €/heure", ""],
      ["Alésage et honnage des cylindres", "70 €/heure", ""],
      ["Rectification du vilebrequin", "70 €/heure", ""],
      ["Remplacement du groupe pistons", "70 €/heure", ""],
      ["Remplacement des coussinets et joints", "70 €/heure", ""],
      ["Remplacement des joints et garnitures", "70 €/heure", ""],
      ["Assemblage et installation du moteur", "500", ""],
      ["🛠 Réparation courante / partielle", "", ""],
      ["Remplacement de la culasse", "70 €/heure", ""],
      ["Remplacement du joint de culasse", "70 €/heure", ""],
      ["Réparation/remplacement des soupapes", "70 €/heure", ""],
      ["Remplacement de la chaîne ou courroie de distribution", "70 €/heure", ""],
      ["Remplacement des tendeurs et galets", "70 €/heure", ""],
      ["Remplacement des compensateurs hydrauliques", "70 €/heure", ""],
      ["Remplacement de la pompe à huile", "70 €/heure", ""],
      ["Réparation du système de refroidissement (pompe, thermostat)", "70 €/heure", ""],
      ["Remplacement des supports moteur (silentblocs)", "70 €/heure", ""],
      ["🧰 Entretien et prévention", "", ""],
      ["Remplacement de l'huile moteur et du filtre à huile", "30", ""],
      ["Remplacement du filtre à air et du filtre à carburant", "30", ""],
      ["📐 Travaux supplémentaires", "", ""],
      ["Vérification des fuites d'huile/liquide de refroidissement", "70 €/heure", ""],
      ["Diagnostic et réparation du système turbo", "70 €/heure", ""],
      ["Nettoyage du collecteur d'admission", "70 €/heure", ""],
      ["Nettoyage des injecteurs", "70 €/heure", ""],
      ["Adaptation et réinitialisation des erreurs ECU", "70 €/heure", ""]
    ]
  },
   "Réparation du châssis": {
    sheetName: "Подвеска",
    data: [
      ["🔍 Diagnostic du train roulant", "", "Si la réparation est faite chez nous, le diagnostic est gratuit"],
      ["Diagnostic complet de la suspension", "50", ""],
      ["Vérification des jeux dans les articulations", "50", ""],
      ["Contrôle de l'état des amortisseurs", "50", ""],
      ["Vérification de l'usure des silentblocs et bagues", "50", ""],
      ["Diagnostic des roulements de roue", "50", ""],
      ["Vérification de l'état des ressorts", "50", ""],
      ["Contrôle de la direction et des barres", "50", ""],
      ["Vérification du système de freinage", "50", ""],
      ["⚙️ Réparation et remplacement des éléments de suspension", "", ""],
      ["Remplacement des amortisseurs", "70 €/heure", ""],
      ["Remplacement des barres stabilisatrices", "70 €/heure", ""],
      ["Remplacement des bras de suspension", "70 €/heure", ""],
      ["Remplacement des silentblocs", "70 €/heure", ""],
      ["Remplacement des rotules", "70 €/heure", ""],
      ["Remplacement des ressorts", "70 €/heure", ""],
      ["Remplacement des sous-châssis", "70 €/heure", ""],
      ["🔄 Direction", "", ""],
      ["Remplacement des barres et rotules de direction", "70 €/heure", ""],
      ["Remplacement de la crémaillère de direction", "70 €/heure", ""],
      ["Réparation/remplacement de la pompe de direction assistée", "70 €/heure", ""],
      ["Remplacement des soufflets de direction", "70 €/heure", ""],
      ["Réparation/remplacement de la direction électrique (EPS)", "70 €/heure", ""],
      ["🛞 Transmission (si nécessaire)", "", ""],
      ["Remplacement des cardans (intérieurs et extérieurs)", "70 €/heure", ""],
      ["Remplacement des soufflets de cardan", "70 €/heure", ""],
      ["Remplacement des arbres et croisillons de transmission", "70 €/heure", ""],
      ["Remplacement des roulements de roue", "70 €/heure", ""],
      ["Remplacement du moyeu complet", "70 €/heure", ""],
      ["🛠 Système de freinage (partie du train roulant)", "", ""],
      ["Remplacement des plaquettes de frein (avant/arrière)", "70 €/heure", ""],
      ["Remplacement des disques et tambours de frein", "70 €/heure", ""],
      ["Remplacement des flexibles de frein", "70 €/heure", ""],
      ["Remplacement ou réparation des étriers", "70 €/heure", ""],
      ["Purge du système de freinage", "70 €/heure", ""],
      ["Remplacement du liquide de frein", "70 €/heure", ""],
      ["⚡ Travaux supplémentaires", "", ""],
      ["Vérification et remplacement des capteurs ABS/ESP", "70 €/heure", ""]
    ]
  },
  "Vidange d'huile": {
    sheetName: "Масло",
    data: [
      ["⚙️ Vidange de la boîte de vitesses", "", ""],
      ["Boîte manuelle :", "", ""],
      ["Vidange de la boîte manuelle", "30", ""],
      ["Contrôle et remplissage de l'huile de transmission", "30", ""],
      ["Boîte automatique :", "", ""],
      ["Vidange partielle de la boîte automatique", "70 €/heure", ""],
      ["Vidange complète avec remplacement du filtre", "70 €/heure", ""],
      ["Vidange avec démontage du carter et nettoyage des aimants", "70 €/heure", ""],
      ["Nettoyage du système hydraulique (si nécessaire)", "70 €/heure", ""],
      ["Réinitialisation des adaptations de la boîte automatique", "70 €/heure", ""],
      ["🔄 Vidange du pont et de la transmission", "", ""],
      ["Vidange de la boîte de transfert", "30", ""],
      ["Vidange du pont avant/arrière", "30", ""],
      ["Contrôle du niveau d'huile du pont", "30", ""],
      ["Diagnostic des fuites", "30", ""],
      ["🧰 Services complémentaires", "", ""],
      ["Révision", "100", ""]
    ]
  },
  "Réparation des freins": {
    sheetName: "Тормоза",
    data: [
      ["🔍 Diagnostic du système de freinage", "", ""],
      ["Contrôle des plaquettes et disques de frein", "70 €/heure", ""],
      ["Vérification des étriers de frein", "70 €/heure", ""],
      ["Diagnostic des flexibles et conduites de frein", "70 €/heure", ""],
      ["Contrôle du servofrein", "70 €/heure", ""],
      ["🛠 Réparation et remplacement des composants", "", ""],
      ["Essieu avant/arrière :", "", ""],
      ["Remplacement des plaquettes de frein", "70 €/heure", ""],
      ["Remplacement des disques de frein", "70 €/heure", ""],
      ["Remplacement des tambours de frein", "70 €/heure", ""],
      ["Remplacement des cylindres de roue", "70 €/heure", ""],
      ["Remplacement des flexibles de frein", "70 €/heure", ""],
      ["Remplacement des tuyaux métalliques", "70 €/heure", ""],
      ["Réparation/remplacement des étriers (glissières, pistons, joints)", "70 €/heure", ""],
      ["🔧 Entretien technique", "", ""],
      ["Purge du système de freinage", "70 €/heure", ""],
      ["Remplacement du liquide de frein", "70 €/heure", ""],
      ["Lubrification des glissières d'étrier", "70 €/heure", ""],
      ["Nettoyage des mécanismes de frein", "70 €/heure", ""],
      ["Élimination des bruits et vibrations", "70 €/heure", ""],
      ["🅿️ Frein à main", "", ""],
      ["Réglage du frein à main", "70 €/heure", ""],
      ["Remplacement des câbles de frein à main", "70 €/heure", ""],
      ["Remplacement des mécanismes de frein à main", "70 €/heure", ""],
      ["Réparation/remplacement du frein à main électrique (EPB)", "70 €/heure", ""],
      ["📌 Services supplémentaires", "", ""],
      ["Contrôle d'étanchéité du système", "70 €/heure", ""],
      ["Réparation des fuites de liquide de frein", "70 €/heure", ""]
    ]
  },
  "Diagnostic auto": {
    sheetName: "Диагностика",
    data: [
      ["🧠 Diagnostic informatique ECU", "", ""],
      ["Scan et lecture des erreurs", "30", ""],
      ["Interprétation des codes défauts (DTC)", "30", ""],
      ["Effacement des erreurs après réparation", "30", ""],
      ["Vérification des paramètres en temps réel", "30", ""],
      ["Diagnostic complet via OBD-II : moteur, boîte, ABS, ESP, airbag, etc.", "30", ""],
      ["🛠 Entretien et adaptation ECU", "", ""],
      ["Réinitialisation des adaptations", "50", ""],
      ["Adaptation du papillon des gaz", "50", ""],
      ["Adaptation de la boîte de vitesses", "50", ""],
      ["Réinitialisation des intervalles d'entretien", "50", ""]
    ]
  }
};